# Generated by Django 4.2.27 on 2025-12-23 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecUserMaster',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('txt_login_id', models.CharField(db_index=True, max_length=48, unique=True)),
                ('password', models.CharField(db_column='txt_user_signature', max_length=128)),
                ('flg_functional_id', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True)),
                ('flg_force_passwd_chg', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('dat_last_passwd_chg', models.DateField(blank=True, null=True)),
                ('txt_user_fname', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_user_mname', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_user_lname', models.CharField(blank=True, max_length=48, null=True)),
                ('enu_user_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N/A', 'Not Applicable')], max_length=4, null=True)),
                ('dat_user_birth', models.DateField(blank=True, null=True)),
                ('id_parent_company_3rdparty', models.BigIntegerField(blank=True, null=True)),
                ('txt_parent_company_name', models.CharField(blank=True, max_length=48, null=True)),
                ('flg_parent_company_verified', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True)),
                ('dat_time_parent_company_verified', models.DateTimeField(blank=True, null=True)),
                ('txt_parent_company_verified_by', models.CharField(blank=True, max_length=48, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('is_enduser', models.BooleanField(blank=True, default=False, null=True)),
                ('is_client', models.BooleanField(blank=True, default=False, null=True)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('is_pass_changed', models.BooleanField(blank=True, default=False, null=True)),
                ('is_2fa', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('txt_employee_id', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_user_email_id', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_user_mobile_phone', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_device_assigned', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_fcm_token', models.TextField(blank=True, null=True)),
                ('dat_time_fcm_expiry', models.DateTimeField(blank=True, null=True)),
                ('cod_home_module', models.CharField(blank=True, max_length=4, null=True)),
                ('cod_home_menu', models.CharField(blank=True, max_length=4, null=True)),
                ('dat_time_t_and_c_accepted', models.DateTimeField(blank=True, null=True)),
                ('dat_time_welcome_dismissed', models.DateTimeField(blank=True, null=True)),
                ('cod_home_branch', models.CharField(blank=True, max_length=6, null=True)),
                ('flg_disabled', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_user_logged_in', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('dat_last_login', models.DateField(blank=True, null=True)),
                ('num_failed_pwd', models.SmallIntegerField(blank=True, null=True)),
                ('dat_profile_created', models.DateField(blank=True, null=True)),
                ('dat_profile_expiry', models.DateField(blank=True, null=True)),
                ('cod_time_zone', models.CharField(blank=True, max_length=4, null=True)),
                ('cod_2fa_question_1', models.CharField(blank=True, max_length=4, null=True)),
                ('txt_2fa_answer_1', models.CharField(blank=True, max_length=48, null=True)),
                ('cod_2fa_question_2', models.CharField(blank=True, max_length=4, null=True)),
                ('txt_2fa_answer_2', models.CharField(blank=True, max_length=48, null=True)),
                ('cod_2fa_question_3', models.CharField(blank=True, max_length=4, null=True)),
                ('txt_2fa_answer_3', models.CharField(blank=True, max_length=48, null=True)),
                ('cod_2fa_question_4', models.CharField(blank=True, max_length=4, null=True)),
                ('txt_2fa_answer_4', models.CharField(blank=True, max_length=48, null=True)),
                ('cod_2fa_question_5', models.CharField(blank=True, max_length=4, null=True)),
                ('txt_2fa_answer_5', models.CharField(blank=True, max_length=48, null=True)),
                ('cod_rec_status', models.CharField(blank=True, choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Rejected'), ('C', 'Closed'), ('X', 'Cancelled')], default='A', max_length=1, null=True)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_credit_officer_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_master_credit_officer', to='masters.mstcreditofficerlevels')),
                ('cod_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_master_department', to='masters.mstdepartments')),
                ('cod_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_master_language', to='masters.mstlanguages')),
                ('cod_user_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_master_designation', to='masters.mstuserdesignation')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('txt_credit_approver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_approved_users', to=settings.AUTH_USER_MODEL)),
                ('txt_default_reviewer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewing_users', to=settings.AUTH_USER_MODEL)),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
                ('txt_manager_login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managing_users', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'sec_user_master',
            },
        ),
        migrations.CreateModel(
            name='SecUserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_photos_default_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('txt_docs_default_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('bin_user_profile_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_css_theme', models.CharField(blank=True, choices=[('DW', 'Default White'), ('DK', 'Dark')], max_length=4, null=True)),
                ('txt_login_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sec_user_preferences',
            },
        ),
        migrations.CreateModel(
            name='SecUserAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_login_id', models.CharField(max_length=48)),
                ('dat_time_login', models.DateTimeField()),
                ('flg_success', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('txt_ip_address_source', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_browser_used', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_os_used', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_user_agent_string', models.TextField(blank=True, null=True)),
                ('txt_login_fail_reason', models.CharField(blank=True, max_length=48, null=True)),
            ],
            options={
                'verbose_name': 'User Access Log',
                'verbose_name_plural': 'User Access Logs',
                'db_table': 'sec_user_access_log',
                'unique_together': {('txt_login_id', 'dat_time_login')},
            },
        ),
        migrations.CreateModel(
            name='SecUserPswdHist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('txt_user_signature', models.CharField(max_length=255)),
                ('dat_passwd_from', models.DateField(blank=True, null=True)),
                ('dat_passwd_to', models.DateField(blank=True, null=True)),
                ('txt_pswd_changed_by', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Password History',
                'verbose_name_plural': 'User Password Histories',
                'db_table': 'sec_user_pswd_hist',
                'indexes': [models.Index(fields=['txt_login_id', 'txt_user_signature', 'dat_passwd_from'], name='idx_sec_user_pswd_hist')],
            },
        ),
        migrations.AddIndex(
            model_name='secusermaster',
            index=models.Index(fields=['txt_login_id'], name='sec_user_ma_txt_log_cd1f93_idx'),
        ),
        migrations.AddIndex(
            model_name='secusermaster',
            index=models.Index(fields=['cod_rec_status'], name='sec_user_ma_cod_rec_5cd58e_idx'),
        ),
    ]
