# Generated by Django 4.2.27 on 2025-12-23 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='secmenuoptions',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secmenuoptions',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstuserdesignation',
            name='cod_parent_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_designations_list', to='masters.mstuserdesignation'),
        ),
        migrations.AddField(
            model_name='mstuserdesignation',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstuserdesignation',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mststatecodes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mststatecodes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstmajorcity',
            name='cod_city',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_city', to='masters.mstcityclasses'),
        ),
        migrations.AddField(
            model_name='mstmajorcity',
            name='cod_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_cities_lists_country', to='masters.mstcountrycodes'),
        ),
        migrations.AddField(
            model_name='mstmajorcity',
            name='cod_state_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_cities_lists_state', to='masters.mststatecodes'),
        ),
        migrations.AddField(
            model_name='mstmajorcity',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstmajorcity',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstlanguages',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstlanguages',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdistrictcodes',
            name='cod_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts_list_country', to='masters.mstcountrycodes'),
        ),
        migrations.AddField(
            model_name='mstdistrictcodes',
            name='cod_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts_list_state', to='masters.mststatecodes'),
        ),
        migrations.AddField(
            model_name='mstdistrictcodes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdistrictcodes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdisclosures',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdisclosures',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdisclosurelang',
            name='cod_disclosure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disclosure_lang', to='masters.mstdisclosures'),
        ),
        migrations.AddField(
            model_name='mstdisclosurelang',
            name='cod_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disclosure_lang', to='masters.mstlanguages'),
        ),
        migrations.AddField(
            model_name='mstdisclosurelang',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdisclosurelang',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdisabilitycodes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdisabilitycodes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdepartmentsupportteam',
            name='cod_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_support_team', to='masters.mstdepartments'),
        ),
        migrations.AddField(
            model_name='mstdepartmentsupportteam',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdepartmentsupportteam',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdepartments',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdepartments',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcurrency',
            name='cod_country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_currency', to='masters.mstcountrycodes'),
        ),
        migrations.AddField(
            model_name='mstcurrency',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcurrency',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcreditofficerlevels',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcreditofficerlevels',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcountrycodes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcountrycodes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcollateraltypes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcollateraltypes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcityclasses',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcityclasses',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstaudittypes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstaudittypes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstauditchecklist',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstauditchecklist',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstaddrtypes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstaddrtypes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='secmenuoptions',
            unique_together={('cod_menu_option', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstuserdesignation',
            unique_together={('cod_designation', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mststatecodes',
            unique_together={('cod_state', 'cod_country', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstmajorcity',
            unique_together={('cod_city', 'cod_country', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstlanguages',
            unique_together={('cod_language', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstdistrictcodes',
            unique_together={('cod_district', 'cod_state', 'cod_country', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstdisclosures',
            unique_together={('cod_disclosure', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstdisclosurelang',
            unique_together={('cod_disclosure', 'cod_language', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstdisabilitycodes',
            unique_together={('cod_disability', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstdepartmentsupportteam',
            unique_together={('cod_department', 'txt_login_id', 'cod_rec_status', 'id_third_party')},
        ),
        migrations.AlterUniqueTogether(
            name='mstdepartments',
            unique_together={('cod_department', 'id_third_party', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstcurrency',
            unique_together={('cod_currency', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstcreditofficerlevels',
            unique_together={('cod_credit_officer_level', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstcountrycodes',
            unique_together={('cod_country', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstcollateraltypes',
            unique_together={('cod_coll_type', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstcityclasses',
            unique_together={('cod_city_class', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstaudittypes',
            unique_together={('cod_audit_type', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstauditchecklist',
            unique_together={('cod_audit_item', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstaddrtypes',
            unique_together={('cod_addr_type', 'cod_rec_status')},
        ),
    ]
