# Generated by Django 4.2.27 on 2025-12-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MstCollateralTypes',
        ),
    ]
