# Generated by Django 4.2.27 on 2025-12-27 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0003_delete_mstcollateraltypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstPinCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_pin_code', models.CharField(max_length=8)),
                ('txt_district_name', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_city_name', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_post_office_name', models.CharField(blank=True, max_length=48, null=True)),
                ('num_longitude', models.FloatField(blank=True, null=True)),
                ('num_latitude', models.FloatField(blank=True, null=True)),
                ('flg_default_value', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pincodes', to='masters.mstcountrycodes')),
                ('cod_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pincodes', to='masters.mstdistrictcodes')),
                ('cod_state_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pincodes', to='masters.mststatecodes')),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PIN Code',
                'verbose_name_plural': 'PIN Codes',
                'db_table': 'mst_pin_codes',
                'unique_together': {('cod_pin_code', 'cod_country', 'cod_rec_status')},
            },
        ),
    ]
