# Generated by Django 4.2.27 on 2025-12-31 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0004_mstpincodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstTimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_time_zone', models.CharField(max_length=4)),
                ('txt_time_zone_name', models.CharField(blank=True, max_length=48, null=True)),
                ('num_hours_gmt_offset', models.FloatField(blank=True, null=True)),
                ('flg_daylight_savings', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_default_value', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Zone',
                'verbose_name_plural': 'Time Zones',
                'db_table': 'mst_time_zones',
                'unique_together': {('cod_time_zone', 'cod_rec_status')},
            },
        ),
    ]
