# Generated by Django 4.2.27 on 2026-01-05 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_alter_cmpcampaigns_bin_logo_to_display'),
        ('masters', '0005_msttimezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstdepartments',
            name='id_third_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments', to='campaign.mstthirdparties'),
        ),
    ]
