# Generated by Django 4.2.27 on 2025-12-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecUserRoleDisclosures',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cod_disclosure', models.CharField(max_length=4)),
                ('num_sequence', models.SmallIntegerField(blank=True, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Role Disclosure',
                'verbose_name_plural': 'User Role Disclosures',
                'db_table': 'sec_user_role_disclosures',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SecUserRoleMenus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cod_menu_option', models.CharField(max_length=4)),
                ('num_display_order', models.SmallIntegerField(blank=True, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sec_user_role_menus',
            },
        ),
        migrations.CreateModel(
            name='SecUserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_user_role', models.CharField(max_length=4)),
                ('txt_user_role_desc', models.CharField(blank=True, max_length=48, null=True)),
                ('cod_home_menu', models.CharField(blank=True, max_length=4, null=True)),
                ('flg_hr_admin', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_sec_admin', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_sysadmin', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_self_service_role', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_default_value', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('num_time_start_wkday', models.SmallIntegerField(default=800)),
                ('num_time_end_wkday', models.SmallIntegerField(default=1800)),
                ('num_time_start_wkend', models.SmallIntegerField(default=800)),
                ('num_time_end_wkend', models.SmallIntegerField(default=1300)),
                ('num_time_start_holiday', models.SmallIntegerField(default=0)),
                ('num_time_end_holiday', models.SmallIntegerField(default=0)),
                ('num_seconds_inactivity_timeout', models.SmallIntegerField(default=300)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'sec_user_roles',
            },
        ),
        migrations.CreateModel(
            name='SecUserXRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_login_id', models.CharField(max_length=48)),
                ('dat_time_disclosure_ack', models.DateTimeField(blank=True, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_user_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_x_roles', to='roles.secuserroles')),
            ],
            options={
                'verbose_name': 'User Role Mapping',
                'verbose_name_plural': 'User Role Mappings',
                'db_table': 'sec_user_x_roles',
            },
        ),
    ]
