# Generated by Django 4.2.27 on 2025-12-23 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuserxroles',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secuserxroles',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secuserroles',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secuserroles',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secuserrolemenus',
            name='cod_user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_menus', to='roles.secuserroles'),
        ),
        migrations.AddField(
            model_name='secuserrolemenus',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secuserrolemenus',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secuserroledisclosures',
            name='cod_user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_disclosures', to='roles.secuserroles'),
        ),
        migrations.AddField(
            model_name='secuserroledisclosures',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secuserroledisclosures',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='secuserxroles',
            unique_together={('txt_login_id', 'cod_user_role', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='secuserroles',
            unique_together={('cod_user_role', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='secuserrolemenus',
            unique_together={('cod_user_role', 'cod_menu_option', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='secuserroledisclosures',
            unique_together={('cod_disclosure', 'cod_user_role', 'cod_rec_status')},
        ),
    ]
