pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/mrnagarjuna/Satisactual.git'
            }
        }

        stage('Stop Old Containers') {
            steps {
                sh 'docker compose down -v || true'
            }
        }

        stage('Build & Deploy') {
            steps {
                sh 'docker compose build'
                sh 'docker compose up -d'
            }
        }

        stage('Status') {
            steps {
                sh 'docker compose ps'
            }
        }
    }
}
