pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/mrnagarjuna/Satisactual.git'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                  docker-compose down -v || true
                  docker-compose build
                  docker-compose up -d
                '''
            }
        }
    }
}
