# Generated by Django 4.2.27 on 2025-12-26 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_mstpromocodes'),
        ('masters', '0003_delete_mstcollateraltypes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0003_mstthirdpartytypes_mstthirdparties'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpCampaigns',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('txt_campaign_name', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_campaign_short_code', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_campaign_title', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_campaign_subtitle', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_campaign_desc', models.TextField(blank=True, null=True)),
                ('enu_campaign_status', models.CharField(choices=[('D', 'Design'), ('W', 'Waiting Approval'), ('A', 'Active'), ('R', 'Response Monitoring'), ('X', 'Closed')], default='D', max_length=1)),
                ('flg_model_campaign', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_targeted_list', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('dat_start', models.DateField(blank=True, null=True)),
                ('dat_end', models.DateField(blank=True, null=True)),
                ('txt_camp_mgr_id', models.CharField(blank=True, max_length=48, null=True)),
                ('id_commissioned_by_thirdparty', models.BigIntegerField(blank=True, null=True)),
                ('bin_logo_to_display', models.CharField(blank=True, max_length=255, null=True)),
                ('txt_invoice_sent_to_id', models.CharField(blank=True, max_length=48, null=True)),
                ('flg_voice_recording_consent', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('flg_video_recording_consent', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_nonconsent_terminate', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('flg_anonymize_names', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_anonymous_response_check', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('flg_allow_clarif_contact_check', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_allow_secure_print', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_proof_before_submit', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_invite_bids', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('num_tot_response_reqd', models.IntegerField(blank=True, null=True)),
                ('num_attempts_per_item', models.SmallIntegerField(default=6)),
                ('num_hours_between_attempts', models.SmallIntegerField(default=24)),
                ('num_archival_months', models.SmallIntegerField(default=24)),
                ('num_est_target_population', models.IntegerField(blank=True, null=True)),
                ('num_confidence_level', models.FloatField(default=97)),
                ('num_margin_of_error', models.FloatField(default=5)),
                ('num_z_score_calc', models.FloatField(blank=True, null=True)),
                ('num_sample_size', models.IntegerField(blank=True, null=True)),
                ('num_est_contact_pct', models.SmallIntegerField(blank=True, null=True)),
                ('num_est_response_pct', models.FloatField(blank=True, null=True)),
                ('num_est_apply_pct', models.FloatField(blank=True, null=True)),
                ('num_est_purchase_pct', models.SmallIntegerField(blank=True, null=True)),
                ('amt_est_rev_per_purchase', models.FloatField(blank=True, null=True)),
                ('dat_created', models.DateField(blank=True, null=True)),
                ('txt_qa_review_proc_name', models.CharField(blank=True, max_length=96, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_campaign_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign', to='campaign.mstcampaigntypes')),
                ('cod_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign', to='masters.mstdepartments')),
                ('cod_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign', to='masters.mstlanguages')),
                ('cod_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign', to='product.mstprodcodes')),
                ('cod_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign', to='product.mstpromocodes')),
                ('txt_created_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'cmp_campaigns',
            },
        ),
    ]
