# Generated by Django 4.2.27 on 2026-01-03 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_msttimezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0004_cmpcampaigns'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpCampaignUserGeoCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_city_name', models.CharField(default='', max_length=96)),
                ('num_priority_sequence', models.SmallIntegerField(default=1)),
                ('num_allocated', models.SmallIntegerField(blank=True, null=True)),
                ('cod_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_geo_coverage', to='masters.mstcountrycodes')),
                ('cod_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_geo_coverage', to='masters.mstdistrictcodes')),
                ('cod_pin_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_geo_coverage', to='masters.mstpincodes')),
                ('cod_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_geo_coverage', to='masters.mststatecodes')),
                ('id_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_geo_coverage', to='campaign.cmpcampaigns')),
                ('txt_login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_geo_coverage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign User Geo Coverage',
                'verbose_name_plural': 'Campaign User Geo Coverage',
                'db_table': 'cmp_campaign_user_geo_coverage',
                'unique_together': {('txt_login_id', 'cod_country', 'cod_state', 'cod_district', 'txt_city_name', 'cod_pin_code', 'id_campaign')},
            },
        ),
    ]
