# Generated by Django 4.2.27 on 2026-01-05 09:24

from django.db import migrations, models
import utils.management.file_rename


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_cmpcampaignusergeocoverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpcampaigns',
            name='bin_logo_to_display',
            field=models.ImageField(blank=True, null=True, upload_to=utils.management.file_rename.upload_to_logo_image),
        ),
    ]
