# Generated by Django 4.2.27 on 2025-12-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MstContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_channel', models.CharField(max_length=4)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('txt_channel_desc', models.CharField(blank=True, max_length=48, null=True)),
                ('flg_default_value', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('enu_base_channel', models.CharField(choices=[('EML', 'Email'), ('PHN', 'Phone'), ('SMS', 'SMS'), ('FLD', 'Field'), ('WEB', 'Web'), ('FBK', 'Facebook'), ('MAL', 'Mail'), ('STR', 'Store')], max_length=4, null=True)),
                ('flg_email_supported', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_SMS_supported', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_auto_dialer_supported', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('cod_auto_dialer', models.CharField(blank=True, max_length=4, null=True)),
                ('enu_mail_protocol', models.CharField(choices=[('S', 'SMTP'), ('E', 'Exchange'), ('O', 'Other')], default='S', max_length=1)),
                ('txt_email_id_for_send', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_email_signature', models.TextField(blank=True, null=True)),
                ('txt_email_signature_2fa', models.TextField(blank=True, null=True)),
                ('txt_smtp_client', models.CharField(blank=True, max_length=255, null=True)),
                ('flg_enable_ssl', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('num_smtp_port', models.SmallIntegerField(default=25)),
                ('txt_pop3_username', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_pop3_client', models.CharField(blank=True, max_length=255, null=True)),
                ('num_pop3_port', models.SmallIntegerField(default=995)),
                ('txt_pop3_encryption', models.CharField(blank=True, max_length=4, null=True)),
                ('txt_imap_username', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_imap_client', models.CharField(blank=True, max_length=255, null=True)),
                ('num_imap_port', models.SmallIntegerField(default=993)),
                ('txt_imap_encryption', models.CharField(blank=True, max_length=4, null=True)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_contact_channel',
            },
        ),
        migrations.CreateModel(
            name='MstContactOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_contact_outcome', models.CharField(max_length=4)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('txt_contact_outcome_desc', models.CharField(blank=True, max_length=96, null=True)),
                ('cod_parent_outcome', models.CharField(blank=True, max_length=4, null=True)),
                ('enu_base_channel_type', models.CharField(choices=[('EML', 'Email'), ('PHN', 'Phone'), ('SMS', 'SMS'), ('FLD', 'Field'), ('WEB', 'Web'), ('FBK', 'Facebook'), ('MAL', 'Mail'), ('STR', 'Store')], max_length=4, null=True)),
                ('flg_valid_outcome', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('flg_retry', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('flg_use_for_followup', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('flg_outbound', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_contact_outcome',
            },
        ),
        migrations.CreateModel(
            name='MstContractEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_event', models.CharField(max_length=4)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('txt_event_desc', models.CharField(max_length=48)),
                ('flg_owners_alerts', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_default_value', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_contract_events',
            },
        ),
        migrations.CreateModel(
            name='MstContractTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_contract_type', models.CharField(max_length=4)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('txt_contract_type_desc', models.CharField(blank=True, max_length=48, null=True)),
                ('flg_default_value', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_contract_types',
            },
        ),
    ]
