# Generated by Django 4.2.27 on 2025-12-23 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstcontracttypes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcontracttypes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcontractevents',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcontractevents',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcontactoutcome',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcontactoutcome',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcontactchannel',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcontactchannel',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mstcontracttypes',
            unique_together={('cod_contract_type', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstcontractevents',
            unique_together={('cod_event', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstcontactoutcome',
            unique_together={('cod_contact_outcome', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstcontactchannel',
            unique_together={('cod_channel', 'cod_rec_status')},
        ),
    ]
