# Generated by Django 4.2.27 on 2025-12-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mstcontracttypes',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mstcontracttypes',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='mstcontracttypes',
            name='txt_last_maker_id',
        ),
        migrations.DeleteModel(
            name='MstContractEvents',
        ),
        migrations.DeleteModel(
            name='MstContractTypes',
        ),
    ]
