# Generated by Django 4.2.27 on 2025-12-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MstQuestionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_question_class', models.CharField(max_length=4)),
                ('txt_question_class_desc', models.CharField(blank=True, max_length=48, null=True)),
                ('num_display_sequence', models.SmallIntegerField(default=1)),
                ('flg_default_value', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Question Class',
                'verbose_name_plural': 'Question Classes',
                'db_table': 'mst_question_classes',
            },
        ),
        migrations.CreateModel(
            name='MstQuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_question_type', models.CharField(max_length=4)),
                ('enu_base_question_type', models.CharField(choices=[('H', 'Header'), ('I', 'Interval'), ('R', 'Rating'), ('O', 'Ordinal'), ('N', 'Nominal'), ('X', 'Match')], default='N', max_length=1)),
                ('txt_question_type_desc', models.CharField(blank=True, max_length=48, null=True)),
                ('enu_display_type', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('GL', 'Grid List'), ('GM', 'Grid Matrix'), ('GS', 'Grid Scale'), ('GX', 'Grid Custom'), ('L', 'List'), ('M', 'Multiple'), ('N', 'Numeric'), ('R', 'Range'), ('RL', 'Rating List'), ('S', 'Single'), ('T', 'Text'), ('AV', 'Audio/Video'), ('CUSTOM', 'Custom')], max_length=10, null=True)),
                ('num_display_order', models.SmallIntegerField(blank=True, null=True)),
                ('num_max_chars_response', models.SmallIntegerField(default=255)),
                ('txt_response_format', models.CharField(blank=True, max_length=255, null=True)),
                ('flg_rating_base_zero', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_rating_one_highest', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('txt_high_rating_label', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_low_rating_label', models.CharField(blank=True, max_length=48, null=True)),
                ('num_rating_levels', models.SmallIntegerField(default=5)),
                ('enu_report_format', models.CharField(blank=True, choices=[('TBL', 'Table'), ('BAR', 'Bar'), ('PIE', 'Pie'), ('CLOUD', 'Cloud'), ('TIME', 'Time'), ('HEAT', 'Heat'), ('GEO', 'Geo')], max_length=10, null=True)),
                ('flg_av_recording_reqd', models.CharField(choices=[('A', 'Audio'), ('V', 'Video'), ('P', 'Photo'), ('N', 'None')], default='N', max_length=1)),
                ('flg_simple_question', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('bin_question_icon', models.TextField(blank=True, null=True)),
                ('flg_default_value', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_question_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_types', to='questionnaries.mstquestionclass')),
            ],
            options={
                'db_table': 'mst_question_types',
            },
        ),
    ]
