# Generated by Django 4.2.27 on 2025-12-24 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0003_delete_mstcollateraltypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstProdCodes',
            fields=[
                ('cod_product', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('enu_product_type', models.CharField(choices=[('CAS', 'Current & Savings'), ('CRD', 'Credit Card'), ('FD', 'Fixed Deposit'), ('LON', 'Loan'), ('MTG', 'Mortgage'), ('INS', 'Insurance'), ('INV', 'Investment'), ('PEN', 'Pension'), ('OTH', 'Other')], default='CAS', max_length=3)),
                ('txt_product_name', models.CharField(max_length=48)),
                ('dat_prod_offer_start', models.DateField(blank=True, null=True)),
                ('dat_prod_offer_end', models.DateField(blank=True, null=True)),
                ('flg_apply_selfserve_mode', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_sales_certif_reqd', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_e_stmt_avlbl', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('bin_product_brochure', models.CharField(blank=True, max_length=255, null=True)),
                ('bin_product_soc', models.CharField(blank=True, max_length=255, null=True)),
                ('bin_product_mitc', models.CharField(blank=True, max_length=255, null=True)),
                ('txt_mktg_tag_line', models.CharField(blank=True, max_length=255, null=True)),
                ('id_eligibility_questionnaire', models.BigIntegerField(default=0)),
                ('num_eligibility_score_min', models.SmallIntegerField(default=9999)),
                ('txt_gen_appl_num_func', models.CharField(blank=True, max_length=255, null=True)),
                ('txt_gen_acct_num_func', models.CharField(blank=True, max_length=255, null=True)),
                ('flg_default_value', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod_codes', to='masters.mstcurrency')),
                ('cod_parent_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_product', to='product.mstprodcodes')),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Code',
                'verbose_name_plural': 'Product Codes',
                'db_table': 'mst_prod_codes',
                'unique_together': {('cod_product', 'cod_rec_status')},
            },
        ),
    ]
