# Generated by Django 4.2.27 on 2025-12-26 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mstprodcodes',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='MstProdDisclosures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_disclosure', models.CharField(max_length=4)),
                ('num_sequence', models.SmallIntegerField(blank=True, null=True)),
                ('flg_all_applicants_mandatory', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_guarantors_mandatory', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_product', models.ManyToManyField(blank=True, related_name='prod_disclosures', to='product.mstprodcodes')),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Disclosure',
                'verbose_name_plural': 'Product Disclosures',
                'db_table': 'mst_prod_disclosures',
                'unique_together': {('cod_disclosure', 'cod_rec_status')},
            },
        ),
    ]
