# Generated by Django 4.2.27 on 2025-12-26 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_alter_mstprodcodes_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstProdDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_doc_type', models.CharField(max_length=4)),
                ('enu_doc_purpose', models.CharField(choices=[('I', 'Initiation'), ('A', 'Account Opening'), ('S', 'Submission'), ('C', 'Closure'), ('T', 'Top-up'), ('P', 'Post Disbursement'), ('M', 'Modification'), ('U', 'Updation'), ('F', 'Foreclosure'), ('V', 'Verification'), ('G', 'General')], default='I', max_length=1)),
                ('flg_acct_opening_doc', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('num_days_from_acct_opening', models.SmallIntegerField(default=-1)),
                ('flg_renewal_doc', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('enu_post_disb_resubmit_freq', models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('H', 'Half-Yearly'), ('A', 'Annually'), ('O', 'Others')], default='X', max_length=1)),
                ('flg_mandatory', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_product', models.ManyToManyField(blank=True, related_name='prod_docs', to='product.mstprodcodes')),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Document',
                'verbose_name_plural': 'Product Documents',
                'db_table': 'mst_prod_docs',
            },
        ),
    ]
