# Generated by Django 4.2.27 on 2025-12-26 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_mstproddocs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstPromoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_promo', models.CharField(max_length=4)),
                ('txt_promo_code_desc', models.CharField(blank=True, max_length=96, null=True)),
                ('flg_default_value', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True)),
                ('dat_promo_start', models.DateField(blank=True, null=True)),
                ('dat_promo_end', models.DateField(blank=True, null=True)),
                ('txt_promo_headline', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_promo_tagline', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_promo_offer_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('bin_promo_creative', models.CharField(blank=True, max_length=255, null=True)),
                ('bin_promo_creative_small', models.CharField(blank=True, max_length=255, null=True)),
                ('flg_customer_facing', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, null=True)),
                ('num_promo_priority', models.SmallIntegerField(blank=True, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='product.mstprodcodes')),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'db_table': 'mst_promo_codes',
                'unique_together': {('cod_promo', 'cod_rec_status')},
            },
        ),
    ]
